#!/bin/sh
. "$(dirname $0)/_/husky.sh"

echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>> 1 <<<<<<<<<<<<<<<<<<<<<<<"
env
if [ "$HUSKY" = "0" ]; then
  echo "HUSKY env variable is set to 0, skipping "$(basename "$0")" hook"
else
  git secrets --prepare_commit_msg_hook -- "$@"
fi
