---
name: CI

on:
  push:
    branches:
      - 'develop'
      - 'bugfix/**'
      - 'dependabot/*'
      - 'feature/**'

jobs:
  unit_tests:
    name: Unit tests
    runs-on: ubuntu-latest
    env:
      FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
      FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
      FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
      FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Compile
        run: yarn install
      - name: Unit tests
        run: yarn test
        if: github.event_name == 'push' && github.ref != 'refs/heads/develop'
      - name: Unit tests with coverage
        uses: paambaati/codeclimate-action@v3.0.0
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: yarn test
          debug: true
