on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - develop

jobs:
  build-prod:
    name: Build and test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build:prod
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test
        env:
          FIREBASE_API_KEY: ${{ FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ FIREBASE_AUTH_DOMAIN }}
          FIREBASE_DATABASE_URL: ${{ FIREBASE_DATABASE_URL }}
          FIREBASE_PROJECT_ID: ${{ FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ FIREBASE_APP_ID }}
          FIREBASE_MEASUREMENT_ID: ${{ FIREBASE_MEASUREMENT_ID }}
